apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntv-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: INVENTORY_FILE
              value: /etc/ntv/inventory.demo.yaml # matches sflow-gen
