apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntv-api
spec:
  template:
    spec:
      containers:
        - name: api
          volumeMounts:
            - name: geoip
              mountPath: /data/geoip
              readOnly: true
      volumes:
        - name: geoip
          persistentVolumeClaim:
            claimName: ntv-geoip
